---
title: "Figure_2"
author: "Magda Cardozo"
date: "18/11/2019"
output: html_document
---

## Load required libraries

```{r }
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(cowplot))
suppressPackageStartupMessages(library(tidyr))
```

## Load data
```{r data}
load("Abundances.RData")
```

## Plot EUB and ARCH profiles by region

```{r plot}
DAPI_vertical_boxplot <- ggplot(counts_all, aes(x= Region, y = DAPI.conc.mn))+
  geom_boxplot(aes(fill = Region))+
  facet_grid(Depth~.)+
  geom_jitter(aes(x= Region, y = DAPI.conc.mn),width = 0.2, alpha = 0.3)+
  geom_signif(comparisons = list(c("EGC", "WSC"),c("EGC","N"),c("N","WSC")), 
              map_signif_level=TRUE, test = "wilcox.test")+
  scale_y_log10(name = "cell concentration (cells/mL)")+
  scale_fill_manual(values=c("WSC" = "red", "EGC" = "blue", "N" = "gray")) +
  theme_bw()+
  coord_flip()+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),legend.position = "none")

counts_all%>% 
  filter(Domain %in% c("EUB","ARCH"))%>%
  group_by(Region, StationName, Depth, Domain) -> EUB_ARCH_absolute

p <- list()
for (i in c("EUB","ARCH")){
  p[[i]] <-  ggplot(counts_all[counts_all$Domain== i,], aes(x= Region, y = FISH.conc.mn))+
    geom_boxplot(aes(fill = Region))+
    facet_grid(Depth~.)+
    geom_jitter(aes(x= Region, y = FISH.conc.mn),width = 0.2, alpha = 0.3)+
    geom_signif(comparisons = list(c("EGC", "WSC"),c("EGC","N"),c("N","WSC")), 
                map_signif_level=TRUE, test = "wilcox.test")+
    scale_y_log10(name = "cell abundance (cells/mL)")+
    scale_fill_manual(values=c("WSC" = "red", "EGC" = "blue", "N" = "gray")) +
    theme_bw()+
    coord_flip()+
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),legend.position = "none")
}

plot_grid(DAPI_vertical_boxplot, p[["EUB"]],p[["ARCH"]], ncol =3, labels = "auto")

dev.copy2eps(device= postscript, file ="./Figure-2.eps")
dev.off()

```

save the figure

```{r psave}
ggsave("Figure-2.pdf", 
       plot = last_plot(),
       scale = 1,
       units = "cm",
       #width = 17.8,
       #height = 17.4,
       dpi = 300)
```