---
title: "Figure_3"
author: "Magda Cardozo"
date: "18/11/2019"
output: html_document
---

## Load required libraries

```{r }
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(cowplot))
suppressPackageStartupMessages(library(tidyr))
```

## Load data
```{r data}
load("Abundances.RData")
```

## Depth profiles and taxa

Define depth profiles by taxa 
```{r tx}
taxa.depth <- c("SAR11", "BACT", "GAM", "CREN",  "VER", "DELTA", "SAR324", "SAR202", "SAR406")
```

Calculate mean counts and adjust the depth
```{r cn}
depth_FISH_by_regions <- counts_all%>% ungroup() %>% 
  filter(Domain %in% taxa.depth) %>% 
  group_by(Region, Depth, Domain) %>% 
  summarise (mean.abund = mean(FISH.conc.mn),
             se.abund = se(FISH.conc.mn))%>% ungroup() %>% 
  mutate_if(is.factor, as.character) %>% 
  mutate(Depth=replace(Depth, Depth=="SRF", 20),
         Depth=replace(Depth, Depth=="EPI", 100),
         Depth=replace(Depth, Depth=="MESO", 1000),
         Depth=replace(Depth, Depth=="BATHY", 2000)) %>% 
  mutate(Depth = as.numeric(Depth),
         Domain = factor(Domain, levels = c("SAR11","BACT", "GAM", "CREN",  "VER", "OPI","DELTA", "SAR324", "CFX",  "SAR202", "SAR406")))
```

Depth profiles plot 
```{r cnp}
Depth_profiles_abs_abundance.p <- ggplot(depth_FISH_by_regions, aes(y = mean.abund, x = Depth, color = Region, group = Region))+
  geom_point()+
  geom_line()+
  #stat_smooth(method = "glm", formula = y ~ poly(x, 3), se = FALSE)+
  #geom_line(data = spline_int, aes(x = x, y = y))+
  #geom_smooth(aes(colour = Region), method = "auto")+
  scale_y_log10()+
  scale_x_reverse()+
  coord_flip()+
  facet_wrap(~Domain)+
  labs(y = "Cell abundance (cells/mL)]", x = "Depth (m)")+
  scale_color_manual(breaks = c("EGC", "N", "WSC"), values = c("blue", "gray", "red"))+
  theme_bw()+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),legend.position = "none")
Depth_profiles_abs_abundance.p
```